import React from 'react'

import styles from './SizeTable.module.css'

const SizeTable = () => {
  return (
    <table className={styles.table}>
      <thead>
        <tr>
          <th>
            Размеры
          </th>
          <th>
            Грудь
          </th>
          <th>
            Талия
          </th>
          <th>
            Бедра
          </th>
          <th>
            Рукав
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>
            <p>
              40
            </p>
          </th>
          <th>
            <p>
              80
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
          <th>
            <p>
              86
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
        </tr>
        <tr>
          <th>
            <p>
              40
            </p>
          </th>
          <th>
            <p>
              80
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
          <th>
            <p>
              86
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
        </tr>
        <tr>
          <th>
            <p>
              40
            </p>
          </th>
          <th>
            <p>
              80
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
          <th>
            <p>
              86
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
        </tr>
        <tr>
          <th>
            <p>
              40
            </p>
          </th>
          <th>
            <p>
              80
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
          <th>
            <p>
              86
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
        </tr>
        <tr>
          <th>
            <p>
              40
            </p>
          </th>
          <th>
            <p>
              80
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
          <th>
            <p>
              86
            </p>
          </th>
          <th>
            <p>
              62
            </p>
          </th>
        </tr>
        
      </tbody>
    </table>
  )
}

export default SizeTable